---
settings:
  name: ONTAP Hardware Systems
  search: ontap-systems,ontap-systems-upgrade,ontap-systems-switches,ontap-metrocluster
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: false
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione sui sistemi hardware ONTAP
    url: "/index.html"
